### ISSUE TITLE
Need feedback on extended example 

### ISSUE THREAD

**Issue by eric-pedersen** [eric-pedersen/mgcv-esa-workshop#10]
Hi folks, @dill @gavinsimpson 

I just pushed a commit with a new extended example for the second part of the day, focusing on non-linear time series data. The compiled script is "example-nonlinear-timeseries.html". It's partially based of the nonlinear trend analysis from Gavin's blog, and partially off the nonlinear analysis of the lynx data set, derived from Cosma Shalizi's blog. I still have to add a reference section to acknowledge both of those; that's on my todo list.

I was looking for feedback on it. Does this seem like a reasonable format for the extended examples? Does it need more explanatory text? Do the exercises make sense? 
Also, putting this together took a fair bit of time, so we may need to trim down the number of extended examples back a bit.

**Comment by gavinsimpson** [comment]
That's a nice example @eric-pedersen but probably a little long. What about splitting the content into two with one on modelling a time series deterministically (the `gamm()`) and the other on the stochastic trend?

The plots should use `ggplot()` not `qplot()` - even Hadley is downplaying `qplot()` now and it won't make the code that much longer.

The examples make sense and there is a good balance between explanation where required and practical stuff.

I'll drop some specific comment in line on the `.Rmd` file.

**Comment by gavinsimpson** [comment]
I've left some notes in-line on the commit: f5bf38320ab52702de302c2d8d09327a839507d6

**Comment by eric-pedersen** [comment]
Thanks for the feedback, Gavin. I've gone through and added a lot of it in.

I figure it'll be easiest to keep this as one example (so there's a shared glossary, etc.), but I made it explicit in the code that people can work through one of the two parts without having to do the other. 

Good suggestion to move away from `qplot` as well. It's a bad habit of mine to use qplot as a shortcut, but it does just end up confusing R neophytes.
