### ISSUE TITLE
Template for slides

### ISSUE THREAD

**Issue by gavinsimpson** [eric-pedersen/mgcv-esa-workshop#11]
Can one of you, perhaps @dill as you have used the HTML slide classes in RStudio more than me, push a file  with a basic YAML header with everything needed for using the HTML slides class we want to use for the materials?

If we're not using the same slide classes then we can ignore this and I'll just use my metropolis-themed beamer slides template.

**Comment by dill** [comment]
Some half-done slides I'd started are at bd68df2d6b4523f0053eb8f2681cc2faacc094bb.

Hopefully this is enough to go off...

FYI: I am on vacation until Saturday morning, with no laptop. So hopefully this is enough! (I am online until midday Tuesday...)
