### ISSUE TITLE
Error when compiling exponential distributions slides

### ISSUE THREAD

**Issue by dill** [eric-pedersen/mgcv-esa-workshop#15]
@eric-pedersen, it seems that there is some error when I get to [line 315 of the beyond the exponential family slides](https://github.com/eric-pedersen/mgcv-esa-workshop/blob/master/slides/04-Beyond_the_exponential_family.Rpres#L315).

```
Error: invalid subscript type 'double'
```

Any ideas? My pipe skills are not as good as yours it would seem!

**Comment by eric-pedersen** [comment]
Looks like I had to force the y variable to be a numeric vector. Sometimes dplyr raises odd errors with regards to variable types, and the solution is generally to force the type to what you want before putting it into the dplyr data frame. Not sure why it didn't raise an error before when I was working on it, but anyway, it's fixed now. See commit [d0543c6](https://github.com/eric-pedersen/mgcv-esa-workshop/commit/d0543c651510e71146c123f853f0b345cdf81d44). 

Let me know if that works for you.
