### ISSUE TITLE
what do we actually have to do?

### ISSUE THREAD

**Issue by dill** [eric-pedersen/mgcv-esa-workshop#2]
I guess it's important to also know what ESA want from us... From [their call for proposals](http://esa.org/ftlauderdale/scientific-program/workshops/), they would like to know:
- Title of the session
- Description of the session (appears online only; 250 words max.)
- Summary sentence (appears in print only; 50 word max.)
- Name and contact information (affiliation, email) for the lead organizer and any co-organizers
- Minimum and maximum number of participants (to assist in room assignment).
- Requested scheduling
- Any additional A/V equipment (standard A/V setup is a screen, LCD projector, and laptop)
- Room set-up desired: theater, conference, hollow square, rounds, other
- Food and beverage requests
- Underwriting of workshop costs by a group or agency
- Is the session intended to be linked to a scientific session?
- Is the session intended to be linked to a business meeting or mixer?
- Describe any known (workshop/event) scheduling conflicts (what should it follow/precede/not conflict with?)

**Comment by eric-pedersen** [comment]
I've just added my proposed description to the master branch. Edit as you both this is necessary. The title I put in is a place-holder; I'm not sure it conveys what we want to do with this workshop clearly. 

For the other details:
- my contact info is: 
  Eric Pedersen
  Center for Limnology
  680 North Park Street
  University of Wisconsin-Madison
  Madison, WI, USA 53704
  eric.pedersen@wisc.edu
- For minimum/maximum participants: I would guess a minimum of 15, max of 30 or so. That seems to be about the limit of what three people can handle for easily for live code demos. 
- We shouldn't need any extra AV equipment, unless we want it recorded for later. If so, camera?
- A conference setup might be easiest, as we could easily move to help people. @gavinsimpson, do you have a suggested setup for this sort of workshop?
- Food and beverage: coffee, at the least. 
- Given that it's last-minute, probably no underwriting, and it's not linked to any session, or mixer.
- No known scheduling conflicts.

**Comment by dill** [comment]
Agree with your assessment @eric-pedersen.

A couple of extra points:
- My affiliation as of January 2016 will be:

David L Miller
Northeast Fisheries Science Center
National Oceanic and Atmospheric Administration
166 Water Street
Woods Hole, MA 02543
- Probably no to the camera (I think it's probably an unnecessary technical overhead)
- I think the numbers are about right
- Happy with @gavinsimpson's recommendation for the room setup

We need to submit this tomorrow (Thursday) right?

**Comment by gavinsimpson** [comment]
- In the past, we've always been stuck with the Rounds set-up. I'd prefer conference - presume they mean rows of tables & chairs.
- Adding coffee etc will add an additional fee to take the workshop. Some observations; the coffee is usually crap (but I'm a bit of a snob) and often facilities on-site or in vicinity for coffee. People will usually bring coffee with them in the morning and it's only 3 hours then to lunch break (and we'd probably schedule a break mid afternoon). I'd suggest that unless there is a strong preference to have it, we keep things cheap for students/post-docs/ECRs and not have coffee supplied.
- My affiliation is:

Gavin L. Simpson
Institute of Environmental Change and Society
University of Regina
3737 Wascana Parkway
Regina
Saskatchewan
S4S 0A2
- Do we need a minimum? 15 seems a little high - I'd do this workshop for anyone interested really, but I tend to arrive on the Friday anyway... If you want a minimum, suggest 10? 30 is OK for the maximum; if we're popular we may get asked to increase when they take stock in the spring.
  - Important to mention that we need Saturday all day as one of the organisers (me) has conflicts with the Advanced Vegan Workshop Proposal on Sunday AM and the ESA Council meeting on Sunday PM.
- I'd say no to the camera - who knows what local laws in place that we might require to navigate re permission to film etc.

**Who is going to be the lead organizer as far as submitting and ESA are concerned?**

**Comment by gavinsimpson** [comment]
One more thing, **Wi-Fi**. I think we should request this clearly as people will inevitably need software updating etc. We had issues last year with ESA not sending us the participant list with email addresses until a day before the workshop, which meant many people didn't get our emails informing them of how to grab the workshop files.

**Comment by eric-pedersen** [comment]
This all sounds fine to me. No coffee and no camera sounds reasonable; conference coffee is often worse than nothing, and everyone should be able to find their own. I agree wi-fi is a priority. I had forgot to list that earlier, but we definitely need a clear request for good wi-fi. 

We do need a minimum. 10 Sounds reasonable, with a max of 30 (and I'd be happy to expand past 30 if we get really high demand). 

As for lead organizer: I'm happy to do the heavy lifting for logistics (given that I'm in country, it might make things a bit easier), but it might make sense to put one of you two down as lead. I don't have nearly as many qualifications as either of you for statistical theory. @gavinsimpson, it might make sense to put you down as lead for name recognition; I suspect quite a few people will look at who the lead is and choose workshops partially on that. 

I think the last thing we need is a _50 word summary sentence_. I don't have time now, as I've got an early morning meeting to get up for, but I'll try and get that done tomorrow following that. 

I'll also edit the check-list above with our answers so whoever ends up as lead and submits has it all in one place.

**Comment by eric-pedersen** [comment]
I've summarized and compiled our discussion here into a single doc with all the requirements except the 50 word summary. I'll add that in tomorrow. 

Cheers,

Eric

**Comment by dill** [comment]
Sounds good to me.

To come back to the "who is in charge" issue, I'm actually not a member of ESA, not sure if that is problematic at this stage -- maybe that means I can't submit the proposal?

Thanks to you both for all your hard work!

**Comment by eric-pedersen** [comment]
As far as I can tell, there's no need for the organizer to be a member, which means any of three of us could do it. Currently I'm not a member either (although I plan to buy a membership for this year).

**Comment by eric-pedersen** [comment]
I've just added the summary sentence to the project-requirements.md file. If you both have a chance, let me know if you think it's clear.

The proposal is due at 5:00 PM EST today (the form will close then). I will submit the application before 4:00 PM EST, as I'm attending a talk from 4:00 PM - 5:00 PM EST. As such, we need to decide by then the last detail (who the lead organizer is). @dill, if Gavin hasn't had a chance to respond by them, are you okay with me putting you in as lead? Again, I'm happy to co-ordinate the back end of things, but the lead should probably be one of the statisticians.

**Comment by dill** [comment]
Yup, no problem for me! Thanks for doing the legwork!

**Comment by gavinsimpson** [comment]
@eric-pedersen I don't mind being the lead-organiser if y'all would prefer.

Just an FYI (as I seem to keep screwing it up every time I submit one of these) the People part of the submission is a real pain. I am now in their system 3 times! When you are adding me, search for `Simpson` (and check Speaker and either Organizer or Co-organizer (as above) and then use the Gavin L. Simpson listed with the `@uregina` address.

**Comment by eric-pedersen** [comment]
Thanks, Gavin. We'll put you down as lead organizer then, and thanks for the heads up about the system; I'll take a bit of extra time on the submission. 

I have a quick meeting now, but I should be back in an hour and get the submission in then, which should leave a fair bit of time to deal with any issues with submission.

**Comment by dill** [comment]
My issue closing-OCD says I should close this. (But do re-open if you think!)
