### ISSUE TITLE
Feedback on proposal

### ISSUE THREAD

**Issue by dill** [eric-pedersen/mgcv-esa-workshop#4]
I've committed my changes. Sorry if it seems like a changed a lot -- I liked the structure, I just tried to tighten things up a little, given our limited word count. I hope this doesn't cause any offense! We now come in at 217, so you can add more details if you think I cut too much! I'll add other thoughts to #2 now...

**Comment by eric-pedersen** [comment]
The changes look great to me! I'm definitely happy with with the edits. It gets the idea across clearly, and hopefully is interesting to our target audience.

**Comment by gavinsimpson** [comment]
Proposal looks good now, succinct and snappy. I fixed a minor typo (7cd6b1bb12777667e7c64d3f6d4e5d3ee6561000) but this is ready to go now I feel. Thanks both of you for doing the heavy lifting with this part (nursing a sick 3 yo at home last night/today).

**Comment by dill** [comment]
Great, thanks for spotting the typo :+1:
