### ISSUE TITLE
Time schedule

### ISSUE THREAD

**Issue by dill** [eric-pedersen/mgcv-esa-workshop#6]
According to https://github.com/eric-pedersen/mgcv-esa-workshop/blob/master/course_outline.md we think everything will happen in the morning... Obviously this is wrong...

Currently we have 2x 4 hour blocks: 8am-12pm and 1pm-5pm set up. I think @gavinsimpson and I implicitly thought of the following structure (tell me if I'm wrong Gavin!):

**Morning**
- Intro (what is a GAM etc)
- Model checking
- Model selection
- Beyond the exponential family

**Afternoon**
- Extended examples/demos (all)
- Smoother zoo

Does this make sense?

If so, we had previous attributed "1 session" to the intro and "1/2 sessions" to the other three sections in the morning. If we then split 4 hours into 2.5 "sessions", we could get to 1.5 hours for the intro, then, 30-45 mins for the other three, we'd have at least a 15 min coffee break. That being said, I think that leaves things a little tight, especially if we want to have some time for practical exercises. I'm going to try to put my intro slides together this weekend/early next week, so I'll have a better idea of how long that first part will be soon, then we can re-jig a bit from there.

Afternoon I think is a bit simpler, as I think the smoother zoo stuff is probably an hour tops, the rest takes as long as it takes but we need to ensure there is plenty of coffee!

**Comment by eric-pedersen** [comment]
This breakdown makes sense to me, and I think it should be pretty doable. I think we should cover the smoother zoo prior to the extended examples, though; I'd guess a lot of examples will depend on knowing a bit about the zoo. 

I think we should make sure we cover the smoother zoo well before covering extended examples; as the examples will be set up as semi-stand alone scripts, if we run out of time to spend on a lot of them, people can try them at home and ask us about them after the course. That'll be harder to do if they don't have a good grasp of the basics.

**Comment by dill** [comment]
I've made some adjustments in 8d319d6 -- I guess this will form the basis of a page on the site for participants...

**Comment by dill** [comment]
Closing this as I think we're done here.
