### ISSUE TITLE
Should we do a quick mailout

### ISSUE THREAD

**Issue by dill** [eric-pedersen/mgcv-esa-workshop#8]
To, say, ECOLOG to advertise the course. Just saw one pop up and realised we've not done much advertising so far...

Happy to write some copy for it, suggestions welcome.

**Comment by gavinsimpson** [comment]
We should check what the current registration list looks like so we can avoid disappointing people if there are but a few spots left. (I know of one workshop that has been cancelled due to email from ESA about low registrations, so I doubt we are under-subscribed, but no point emailing out if we're full.)

I'll drop them a quick email to check.

**Comment by dill** [comment]
Yup, good idea. How do we do that?

**Comment by gavinsimpson** [comment]
I've just emailed ESA - sorry I forgot to indicate that in the initial comment.

**Comment by gavinsimpson** [comment]
ESA just got back to me: we have 15 participants currently registered. That's a nice number to handle but it wouldn't hurt to send out an email or two about the course (and to Twitter). Who will do this?

**Comment by dill** [comment]
I'm happy to do this. Based off what has already been posted on ECOLOG, 
does the below make sense:

ESA 2016: The mgcv package as a one-stop-shop for fitting non-linear 
ecological models (WK2)

Saturday August 7th 8am-5pm
204, Ft Lauderdale Convention Center

Instructors: Eric J Pedersen, Gavin Simpson, David L Miller, Noam Ross

We will be giving a one day course on using the popular R package mgcv 
to build complex (and simple!) ecological models. Our aim is to take 
participants with an understanding of the glm() function in R to the 
point where they can fit generalized additive and random effects models 
using mgcv. We'll be taking data from a number of different ecological 
sources, showing how mgcv can be used in a variety of modelling situations.

Participants should ensure that they are running the latest version of R 
(http://www.r-project.org) and mgcv (running update.packages() in R) on 
their laptops before they arrive.

# 

Detailed workshop description:

To address the increase in both quantity and complexity of available 
data, ecologists require flexible, robust statistical models, as well as 
software to perform such analyses. This workshop will focus on how a 
single tool, the mgcvpackage for the R language, can be used to fit 
models to data from a wide range of sources.

mgcv is one of the most popular packages for modelling non-linear 
relationships. However, many users do not know how versatile and 
powerful a tool it can be. This workshop will focus on teaching 
participants how to use mgcv in a wide variety of situations (including 
spatio-temporal, zero-inflated, heavy-tailed, time series, and survival 
data) and advanced use of mgcv (fitting smooth interactions, seasonal 
effects, spatial effects, Markov random fields and varying-coefficient 
models).

The workshop will give paricipants an understanding of: (a) practical 
elements of smoothing theory, with a focus on why they would choose to 
use different types of smoothers (b) model checking and selection (c) 
the range of modelling possibilities using mgcv. Participants will be 
assumed to be familiar with the basics of R (loading/manipulating data, 
functions, and plotting) and regression in R (lm() and glm()). The 
organizers have extensive practical experience with ecological 
statistics and modelling using mgcv.

**Comment by dill** [comment]
ALSO: Should I also go ahead and generate a *.github.io site for the course?

**Comment by gavinsimpson** [comment]
Cheers @dill Email looks good and having a website is great if you are happy to do it?

**Comment by dill** [comment]
Can do.

@eric-pedersen can you give me admin rights on the repo so I can hit the 
button?

**Comment by eric-pedersen** [comment]
The Ecolog email sounds good to me, @dill. 

From what I can tell, I can't give admin rights to a personal repository without transferring ownership. Our options would be to either create an organization with the three of us as members then give us all admin privileges, transfer control to you, or just going ahead and making the .io page and then I think you can change it. As the last one seems simplest for now, I'll just go ahead and set up the webpage, and then you can push any changes necessary,  @dill. Long term, we should move this to an organization; I think we can have a free organization account as long as we don't have any private repositories.

**Comment by dill** [comment]
Sounds good! Thanks :)

**Comment by eric-pedersen** [comment]
Okay, I've created it; the page is on branch gh-pages, and the website is :[eric-pedersen.github.io/mgcv-esa-workshop/](http://eric-pedersen.github.io/mgcv-esa-workshop/). It should be editable now.

**Comment by dill** [comment]
Okay, great. In my cold-filled stupor I will attempt to make a 
reasonable set of pages and then add this to the ECOLOG mailing and send 
it out.

**Comment by dill** [comment]
I've pushed something barely serviceable there. Please do edit away and 
I'll send out the ECOLOG mailing tomorrow?

**Comment by dill** [comment]
Done! (**And** I corrected the date to the 6th 👍 )
